century_dict = {
    1: "First",
    2: "Second",
    3: "Third",
    4: "Fourth",
    5: "Fifth",
    6: "Sixth",
    7: "Seventh",
    8: "Eighth",
    9: "Nineth",
    10: "Tenth",
    11: "Eleventh",
    12: "Twelth",
    13: "Thirtheenth",
    14: "Fourteenth",
    15: "Fifteenth",
    16: "Sixteenth",
    17: "Seventeenth",
    18: "Eighteenth",
    19: "Nineteenth",
    20: "Twentyth",
    21: "Twentyfirst",
    22: "Twentysecond",
    23: "Twentythird",
    24: "Twentyfourth",
    25: "Twentyfifth",
    26: "Twentysixth",
}

decade_dict = {
    0: "Naughties",
    1: "Tens",
    2: "Twenties",
    3: "Thirties",
    4: "Fourties",
    5: "Fifties",
    6: "Sixties",
    7: "Seventies",
    8: "Eightees",
    9: "Ninetees",
}